version: "3.7"

services:
  fastapi_beanie_app:
    container_name: fastapi_beanie_app
    depends_on:
      - mongo_db
    build: ./
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./app/:/app/
    ports:
      - 8081:8080
    environment:
      - MONGODB_APP_USERNAME=${MONGO_APP_USER}
      - MONGODB_APP_PASSWORD=${MONGO_APP_PASS}
      - MONGODB_URI=mongodb://${MONGO_APP_USERNAME}:${MONGO_APP_PASSWORD}@mongo_db

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    logging:
      options:
        max-size: 10m
    ports: 
      - 27017:27017
    volumes:
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./db/mongo_data/:/data/db
      - ./db/mongo_log/:/var/log/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASS}
      - MONGODB_APP_USERNAME=${MONGO_APP_USER}
      - MONGODB_APP_PASSWORD=${MONGO_APP_PASS}

volumes:
  mongo_data:
    driver: local
  mongo_log:
    driver: local
