apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -c -o fastapi-microservices-helm
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: cast-service
  name: cast-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cast-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -c -o fastapi-microservices-helm
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cast-service
    spec:
      containers:
        - env:
            - name: POSTGRES_USER
              value: ""
            - NAME: POSTGRES_PASSWORD
              value: ""
            - NAME: POSTGRES_CAST_DB
              value: "cast_db"
            - name: DATABASE_URI
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@pgsql-db:5432/$(POSTGRES_CAST_DB)
          image: fastapi-microservices_cast_service:latest
          name: cast-service
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /app/
              name: cast-service-claim0
      restartPolicy: Always
      volumes:
        - name: cast-service-claim0
          persistentVolumeClaim:
            claimName: cast-service-claim0
status: {}
