apiVersion: v1
kind: PersistentVolume
metadata:
name: web-pv0
spec:
capacity:
  storage: 100Mi
volumeMode: Filesystem
accessModes:
  - ReadWriteOnce
persistentVolumeClaimPolicy: Retain
storageClassName: local-storage
local:
  path: /opt/k8s/storage/web-pv0
