# traefik-dev.toml

[entryPoints]
  [entryPoints.web]
    address = ":80"

# Traefik dashboard over http   
[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]

# containers are not disovered automatically
[providers]
  [providers.docker]
    exposedByDefault = false
